name: Download Latest v2rayNG Universal APK

on:
  schedule:
    - cron: '0 0 * * *'  # اجرا هر روز ساعت ۰۰:۰۰ UTC
  workflow_dispatch:     # امکان اجرای دستی

jobs:
  download-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release info
        id: get_release
        run: |
          curl -s https://api.github.com/repos/2dust/v2rayNG/releases/latest > release.json
          tag=$(jq -r '.tag_name' release.json)
          url=$(jq -r '.assets[] | select(.name | test("universal.*\\.apk$")) | .browser_download_url')
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Download APK
        run: |
          mkdir -p public
          wget "${{ steps.get_release.outputs.url }}" -O public/v2rayNG.apk
          echo "Downloaded universal APK for version ${{ steps.get_release.outputs.tag }}"

      - name: Commit and push APK
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add public/v2rayNG.apk || true
          git commit -m "Update to latest universal APK version ${{ steps.get_release.outputs.tag }}" || echo "No changes to commit"
          git push
