name: Download Latest v2rayNG APK

on:
  schedule:
    - cron: '0 0 * * *'  # اجرا هر روز ساعت ۰۰:۰۰ UTC
  workflow_dispatch:     # اجرا دستی از GitHub

jobs:
  download-latest:
    runs-on: ubuntu-latest
    steps:
      - name: دریافت آخرین نسخه
        run: |
          curl -s https://api.github.com/repos/2dust/v2rayNG/releases/latest > release.json
          TAG=$(jq -r '.tag_name' release.json)
          URL=$(jq -r '.assets[] | select(.name | endswith(".apk")) | .browser_download_url')
          mkdir -p public
          wget "$URL" -O public/v2rayNG.apk
          echo "آخرین نسخه $TAG دانلود شد."

      - name: آپلود در ریپو
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add public/v2rayNG.apk || true
          git commit -m "آپدیت به نسخه جدید" || echo "فایلی برای آپدیت نبود"
          git push
